XRD_CONTAINER_VERSION=25.3.1
XRD_CONTAINER_ARCHIVE=xrd-control-plane-container-x64.${XRD_CONTAINER_VERSION}.tgz

SANDBOX_ROOT=/home/developer/XRd-Sandbox

SSH_KEY_PATH=~/.ssh/sandbox_key
SANDBOX_USER=developer
SANDBOX_IP=10.10.20.15

# Logging Configuration
# Set to 1 to enable color output (useful for development in VS Code)
# Set to 0 or leave unset for CI/CD pipelines (default: disabled)
ENABLE_COLOR=${ENABLE_COLOR:-0}

# Log directory structure: ${SANDBOX_ROOT}/logs/YYYY-MM-DD_HH-MM-SS/
LOG_DIR=${SANDBOX_ROOT}/logs

# RUN_ID is auto-generated by Makefile and shared across all steps in a single run
# Format: YYYY-MM-DD_HH-MM-SS (e.g., 2025-12-18_14-30-45)
RUN_ID=${RUN_ID:-}
