#!/usr/bin/env bash

# fix-mgmt-interface.sh
#
# Fixes the XR_MGMT_INTERFACES linux interface name in a docker-compose.yml
# produced by xr-compose.
#
# Problem:
#   xr-compose assigns every Docker network an internal counter-based prefix
#   (e.g. xr-n00, xr-n01, …). The interface name each container sees is that
#   prefix plus a trailing digit, e.g. "xr-n120". The counter depends on the
#   total number of networks in the topology, so it changes whenever the
#   topology grows or shrinks. For data-plane GigabitEthernet interfaces this
#   naming is intentional and must be preserved. However, for the management
#   macvlan network Docker assigns the interface inside the container the
#   standard name "eth0" regardless of the prefix, so XR_MGMT_INTERFACES must
#   reference "linux:eth0", not "linux:xr-nXXX".
#
# Solution:
#   Target only lines that contain XR_MGMT_INTERFACES and replace any
#   occurrence of "linux:xr-n<digits>" with "linux:eth0".  This is topology-
#   and version-agnostic — it does not hard-code the counter value.
#
# Usage (sourced):
#   source /path/to/fix-mgmt-interface.sh
#   fix_mgmt_interface /path/to/docker-compose.yml
#
# Usage (standalone):
#   ./fix-mgmt-interface.sh /path/to/docker-compose.yml

# ---------------------------------------------------------------------------
# Bootstrap: load common utilities if not already available
# ---------------------------------------------------------------------------
_FIX_MGMT_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_FIX_MGMT_COMMON="$_FIX_MGMT_SCRIPT_DIR/common.sh"

# Guard: avoid double-sourcing common.sh (it uses 'readonly' for color vars)
if ! declare -f print_info > /dev/null 2>&1; then
    if [[ -f "$_FIX_MGMT_COMMON" ]]; then
        source "$_FIX_MGMT_COMMON"
    else
        # Minimal fallbacks so the function works even without common.sh
        print_info()    { echo "[INFO] $*"; }
        print_success() { echo "[SUCCESS] $*"; }
        print_warning() { echo "[WARNING] $*"; }
        print_error()   { echo "[ERROR] $*" >&2; }
        log_message()   { :; }
    fi
fi

# ---------------------------------------------------------------------------
# fix_mgmt_interface
#
# Arguments:
#   $1  Path to the docker-compose.yml file to patch (required)
#
# Returns:
#   0   on success
#   1   on error (missing argument, file not found, sed failure, or
#       XR_MGMT_INTERFACES still contains an xr-n interface after patching)
# ---------------------------------------------------------------------------
fix_mgmt_interface() {
    local compose_file="$1"

    if [[ -z "$compose_file" ]]; then
        print_error "fix_mgmt_interface: compose file path is required"
        print_error "Usage: fix_mgmt_interface <path-to-docker-compose.yml>"
        return 1
    fi

    if [[ ! -f "$compose_file" ]]; then
        print_error "fix_mgmt_interface: compose file not found: $compose_file"
        return 1
    fi

    print_info "Fixing XR_MGMT_INTERFACES interface name in: $compose_file"
    log_message "[INFO] Fixing XR_MGMT_INTERFACES interface name in: $compose_file"

    # Apply substitution only on lines that contain XR_MGMT_INTERFACES.
    # The pattern 'xr-n[0-9]+' matches the counter-based name generated by
    # xr-compose (e.g. xr-n120, xr-n30) regardless of topology size.
    if ! sed -i.bak -E '/XR_MGMT_INTERFACES/s/linux:xr-n[0-9]+/linux:eth0/g' \
            "$compose_file"; then
        print_error "fix_mgmt_interface: sed failed on: $compose_file"
        log_message "[ERROR] sed failed on: $compose_file"
        return 1
    fi

    # Verify the substitution was actually applied — any remaining xr-n name
    # on an XR_MGMT_INTERFACES line is a sign the pattern did not match.
    if grep -qE 'XR_MGMT_INTERFACES.*linux:xr-n[0-9]+' "$compose_file"; then
        print_warning "fix_mgmt_interface: XR_MGMT_INTERFACES still contains an xr-n interface name after patching"
        log_message "[WARNING] XR_MGMT_INTERFACES still contains an xr-n interface name after patching"
        return 1
    fi

    print_success "XR_MGMT_INTERFACES updated: linux:xr-n<N> → linux:eth0"
    log_message "[SUCCESS] XR_MGMT_INTERFACES updated to use linux:eth0 in: $compose_file"
    return 0
}

# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    set -euo pipefail

    # CURRENT_LOG_FILE is normally set by init_logging in the calling script.
    # When this script is run standalone (no calling script), initialize it to
    # empty so that log_message (from common.sh) silently skips file writes.
    : "${CURRENT_LOG_FILE:=}"
    export CURRENT_LOG_FILE

    if [[ $# -ne 1 ]]; then
        echo "Usage: $(basename "$0") <path-to-docker-compose.yml>"
        echo ""
        echo "Fixes the XR_MGMT_INTERFACES linux interface name in a docker-compose.yml"
        echo "generated by xr-compose, replacing 'linux:xr-n<N>' with 'linux:eth0'."
        echo ""
        echo "This is needed because xr-compose generates a counter-based name that"
        echo "varies with topology size, but Docker macvlan networks always present"
        echo "as 'eth0' inside the container."
        exit 1
    fi

    fix_mgmt_interface "$1"
fi
